import type { LangCode } from "@/lib/i18n";
import type { Auction } from "@/lib/auctions";

// Conteúdo traduzido dos especialistas FICTÍCIOS (carrossel decorativo da
// home). Nomes próprios (expert) e a plataforma (nome de produto) não mudam
// entre idiomas — apenas o texto descritivo.
type AuctionLocalized = {
  niche: string;
  specialty: string;
  credential: string;
  bio: string;
  languages: string[];
  tags: string[];
  included: string;
  historyAt: string[];
};

export const AUCTION_I18N: Record<LangCode, Record<string, AuctionLocalized>> = {
  "pt-BR": {
    "1": {
      niche: "Saúde",
      specialty: "Cardiologista — check-up executivo",
      credential: "Pós-doc Harvard Medical School",
      bio: "Mais de 22 anos dedicados à cardiologia preventiva de alta performance, atendendo executivos e atletas em São Paulo e Nova York.",
      languages: ["Português", "Inglês"],
      tags: ["Cardiologia", "Check-up", "Prevenção"],
      included: "Análise completa de exames recentes, plano de acompanhamento personalizado e relatório executivo enviado em até 48h.",
      historyAt: ["há 4 min", "há 11 min", "há 28 min", "há 1h"],
    },
    "2": {
      niche: "Música",
      specialty: "Produtor musical — análise de demo",
      credential: "Grammy Latino 2019",
      bio: "Produtor com três décadas no estúdio. Trabalhos com artistas premiados em MPB, jazz e música clássica contemporânea.",
      languages: ["Português", "Inglês", "Espanhol"],
      tags: ["Produção", "Demo", "Mixagem"],
      included: "Escuta crítica da sua demo, sugestões de produção e direção artística em sessão de 90 minutos.",
      historyAt: ["há 12 min", "há 40 min", "há 2h"],
    },
    "3": {
      niche: "Tecnologia",
      specialty: "Arquiteto de software — code review",
      credential: "Ex-Staff Engineer no Google",
      bio: "Especialista em sistemas distribuídos e arquitetura de larga escala. Mentor de fundadores Y Combinator.",
      languages: ["Português", "Inglês"],
      tags: ["Arquitetura", "Code review", "Mentoria"],
      included: "Code review ao vivo, revisão de arquitetura e roteiro de melhorias priorizadas.",
      historyAt: ["há 2 min", "há 18 min", "há 35 min"],
    },
    "4": {
      niche: "Direito",
      specialty: "Direito empresarial e M&A",
      credential: "Sócia em escritório tier-1",
      bio: "Sócia em um dos maiores escritórios do Brasil, especialista em fusões, aquisições e estruturação societária.",
      languages: ["Português", "Inglês"],
      tags: ["M&A", "Societário", "Contratos"],
      included: "Consulta estratégica confidencial com análise prévia dos documentos enviados.",
      historyAt: ["há 22 min", "há 1h", "há 3h"],
    },
  },
  en: {
    "1": {
      niche: "Health",
      specialty: "Cardiologist — executive check-up",
      credential: "Harvard Medical School postdoc",
      bio: "Over 22 years dedicated to high-performance preventive cardiology, treating executives and athletes in São Paulo and New York.",
      languages: ["Portuguese", "English"],
      tags: ["Cardiology", "Check-up", "Prevention"],
      included: "Full review of recent exams, a personalized follow-up plan, and an executive report delivered within 48h.",
      historyAt: ["4 min ago", "11 min ago", "28 min ago", "1h ago"],
    },
    "2": {
      niche: "Music",
      specialty: "Music producer — demo review",
      credential: "2019 Latin Grammy",
      bio: "Producer with three decades in the studio. Worked with award-winning artists in Brazilian pop, jazz, and contemporary classical music.",
      languages: ["Portuguese", "English", "Spanish"],
      tags: ["Production", "Demo", "Mixing"],
      included: "Critical listening of your demo, production suggestions, and artistic direction in a 90-minute session.",
      historyAt: ["12 min ago", "40 min ago", "2h ago"],
    },
    "3": {
      niche: "Technology",
      specialty: "Software architect — code review",
      credential: "Former Staff Engineer at Google",
      bio: "Specialist in distributed systems and large-scale architecture. Mentor to Y Combinator founders.",
      languages: ["Portuguese", "English"],
      tags: ["Architecture", "Code review", "Mentoring"],
      included: "Live code review, architecture review, and a prioritized improvement roadmap.",
      historyAt: ["2 min ago", "18 min ago", "35 min ago"],
    },
    "4": {
      niche: "Law",
      specialty: "Corporate law & M&A",
      credential: "Partner at a tier-1 law firm",
      bio: "Partner at one of Brazil's largest law firms, specializing in mergers, acquisitions, and corporate structuring.",
      languages: ["Portuguese", "English"],
      tags: ["M&A", "Corporate", "Contracts"],
      included: "Confidential strategic consultation with prior review of submitted documents.",
      historyAt: ["22 min ago", "1h ago", "3h ago"],
    },
  },
  es: {
    "1": {
      niche: "Salud",
      specialty: "Cardióloga — chequeo ejecutivo",
      credential: "Postdoctorado en Harvard Medical School",
      bio: "Más de 22 años dedicados a la cardiología preventiva de alto rendimiento, atendiendo a ejecutivos y atletas en São Paulo y Nueva York.",
      languages: ["Portugués", "Inglés"],
      tags: ["Cardiología", "Chequeo", "Prevención"],
      included: "Análisis completo de exámenes recientes, plan de seguimiento personalizado e informe ejecutivo entregado en hasta 48h.",
      historyAt: ["hace 4 min", "hace 11 min", "hace 28 min", "hace 1h"],
    },
    "2": {
      niche: "Música",
      specialty: "Productor musical — análisis de demo",
      credential: "Grammy Latino 2019",
      bio: "Productor con tres décadas en el estudio. Trabajos con artistas premiados en MPB, jazz y música clásica contemporánea.",
      languages: ["Portugués", "Inglés", "Español"],
      tags: ["Producción", "Demo", "Mezcla"],
      included: "Escucha crítica de tu demo, sugerencias de producción y dirección artística en una sesión de 90 minutos.",
      historyAt: ["hace 12 min", "hace 40 min", "hace 2h"],
    },
    "3": {
      niche: "Tecnología",
      specialty: "Arquitecto de software — revisión de código",
      credential: "Ex-Staff Engineer en Google",
      bio: "Especialista en sistemas distribuidos y arquitectura a gran escala. Mentor de fundadores de Y Combinator.",
      languages: ["Portugués", "Inglés"],
      tags: ["Arquitectura", "Revisión de código", "Mentoría"],
      included: "Revisión de código en vivo, revisión de arquitectura y hoja de ruta de mejoras priorizadas.",
      historyAt: ["hace 2 min", "hace 18 min", "hace 35 min"],
    },
    "4": {
      niche: "Derecho",
      specialty: "Derecho empresarial y M&A",
      credential: "Socia en un bufete de primer nivel",
      bio: "Socia en uno de los bufetes más grandes de Brasil, especialista en fusiones, adquisiciones y estructuración societaria.",
      languages: ["Portugués", "Inglés"],
      tags: ["M&A", "Societario", "Contratos"],
      included: "Consulta estratégica confidencial con análisis previo de los documentos enviados.",
      historyAt: ["hace 22 min", "hace 1h", "hace 3h"],
    },
  },
  fr: {
    "1": {
      niche: "Santé",
      specialty: "Cardiologue — bilan de santé exécutif",
      credential: "Post-doctorat à Harvard Medical School",
      bio: "Plus de 22 ans consacrés à la cardiologie préventive de haute performance, au service de dirigeants et d'athlètes à São Paulo et New York.",
      languages: ["Portugais", "Anglais"],
      tags: ["Cardiologie", "Bilan", "Prévention"],
      included: "Analyse complète des examens récents, plan de suivi personnalisé et rapport exécutif livré sous 48h.",
      historyAt: ["il y a 4 min", "il y a 11 min", "il y a 28 min", "il y a 1h"],
    },
    "2": {
      niche: "Musique",
      specialty: "Producteur musical — analyse de démo",
      credential: "Grammy Latino 2019",
      bio: "Producteur avec trois décennies en studio. A travaillé avec des artistes primés en MPB, jazz et musique classique contemporaine.",
      languages: ["Portugais", "Anglais", "Espagnol"],
      tags: ["Production", "Démo", "Mixage"],
      included: "Écoute critique de votre démo, suggestions de production et direction artistique lors d'une session de 90 minutes.",
      historyAt: ["il y a 12 min", "il y a 40 min", "il y a 2h"],
    },
    "3": {
      niche: "Technologie",
      specialty: "Architecte logiciel — revue de code",
      credential: "Ancien Staff Engineer chez Google",
      bio: "Spécialiste des systèmes distribués et de l'architecture à grande échelle. Mentor de fondateurs Y Combinator.",
      languages: ["Portugais", "Anglais"],
      tags: ["Architecture", "Revue de code", "Mentorat"],
      included: "Revue de code en direct, revue d'architecture et feuille de route d'améliorations priorisées.",
      historyAt: ["il y a 2 min", "il y a 18 min", "il y a 35 min"],
    },
    "4": {
      niche: "Droit",
      specialty: "Droit des affaires et fusions-acquisitions",
      credential: "Associée dans un cabinet de premier plan",
      bio: "Associée dans l'un des plus grands cabinets d'avocats du Brésil, spécialisée en fusions, acquisitions et structuration d'entreprises.",
      languages: ["Portugais", "Anglais"],
      tags: ["Fusions-acquisitions", "Droit des sociétés", "Contrats"],
      included: "Consultation stratégique confidentielle avec analyse préalable des documents envoyés.",
      historyAt: ["il y a 22 min", "il y a 1h", "il y a 3h"],
    },
  },
  de: {
    "1": {
      niche: "Gesundheit",
      specialty: "Kardiologin — Executive-Check-up",
      credential: "Postdoc an der Harvard Medical School",
      bio: "Über 22 Jahre in der leistungsorientierten präventiven Kardiologie, mit Patienten aus Führungskräften und Athleten in São Paulo und New York.",
      languages: ["Portugiesisch", "Englisch"],
      tags: ["Kardiologie", "Check-up", "Prävention"],
      included: "Vollständige Analyse aktueller Untersuchungen, individueller Nachsorgeplan und Executive-Bericht innerhalb von 48 Stunden.",
      historyAt: ["vor 4 Min.", "vor 11 Min.", "vor 28 Min.", "vor 1 Std."],
    },
    "2": {
      niche: "Musik",
      specialty: "Musikproduzent — Demo-Analyse",
      credential: "Latin Grammy 2019",
      bio: "Produzent mit drei Jahrzehnten Studioerfahrung. Arbeiten mit preisgekrönten Künstlern in brasilianischem Pop, Jazz und zeitgenössischer klassischer Musik.",
      languages: ["Portugiesisch", "Englisch", "Spanisch"],
      tags: ["Produktion", "Demo", "Mischung"],
      included: "Kritisches Anhören Ihrer Demo, Produktionsvorschläge und künstlerische Leitung in einer 90-minütigen Sitzung.",
      historyAt: ["vor 12 Min.", "vor 40 Min.", "vor 2 Std."],
    },
    "3": {
      niche: "Technologie",
      specialty: "Softwarearchitekt — Code-Review",
      credential: "Ehemaliger Staff Engineer bei Google",
      bio: "Spezialist für verteilte Systeme und Architektur im großen Maßstab. Mentor für Y-Combinator-Gründer.",
      languages: ["Portugiesisch", "Englisch"],
      tags: ["Architektur", "Code-Review", "Mentoring"],
      included: "Live-Code-Review, Architektur-Review und priorisierter Verbesserungsfahrplan.",
      historyAt: ["vor 2 Min.", "vor 18 Min.", "vor 35 Min."],
    },
    "4": {
      niche: "Recht",
      specialty: "Wirtschaftsrecht & M&A",
      credential: "Partnerin in einer erstklassigen Kanzlei",
      bio: "Partnerin in einer der größten Anwaltskanzleien Brasiliens, spezialisiert auf Fusionen, Übernahmen und Unternehmensstrukturierung.",
      languages: ["Portugiesisch", "Englisch"],
      tags: ["M&A", "Gesellschaftsrecht", "Verträge"],
      included: "Vertrauliche strategische Beratung mit vorheriger Prüfung der eingereichten Dokumente.",
      historyAt: ["vor 22 Min.", "vor 1 Std.", "vor 3 Std."],
    },
  },
  it: {
    "1": {
      niche: "Salute",
      specialty: "Cardiologa — check-up executive",
      credential: "Post-dottorato ad Harvard Medical School",
      bio: "Oltre 22 anni dedicati alla cardiologia preventiva ad alte prestazioni, seguendo dirigenti e atleti a San Paolo e New York.",
      languages: ["Portoghese", "Inglese"],
      tags: ["Cardiologia", "Check-up", "Prevenzione"],
      included: "Analisi completa degli esami recenti, piano di follow-up personalizzato e report esecutivo consegnato entro 48h.",
      historyAt: ["4 min fa", "11 min fa", "28 min fa", "1h fa"],
    },
    "2": {
      niche: "Musica",
      specialty: "Produttore musicale — analisi demo",
      credential: "Grammy Latino 2019",
      bio: "Produttore con tre decenni in studio. Ha lavorato con artisti premiati nella MPB, jazz e musica classica contemporanea.",
      languages: ["Portoghese", "Inglese", "Spagnolo"],
      tags: ["Produzione", "Demo", "Missaggio"],
      included: "Ascolto critico della tua demo, suggerimenti di produzione e direzione artistica in una sessione di 90 minuti.",
      historyAt: ["12 min fa", "40 min fa", "2h fa"],
    },
    "3": {
      niche: "Tecnologia",
      specialty: "Architetto software — code review",
      credential: "Ex Staff Engineer a Google",
      bio: "Specialista in sistemi distribuiti e architettura su larga scala. Mentore di fondatori Y Combinator.",
      languages: ["Portoghese", "Inglese"],
      tags: ["Architettura", "Code review", "Mentoring"],
      included: "Code review dal vivo, revisione dell'architettura e roadmap di miglioramenti prioritari.",
      historyAt: ["2 min fa", "18 min fa", "35 min fa"],
    },
    "4": {
      niche: "Diritto",
      specialty: "Diritto commerciale e M&A",
      credential: "Socia in uno studio legale di prim'ordine",
      bio: "Socia in uno dei più grandi studi legali del Brasile, specializzata in fusioni, acquisizioni e strutturazione societaria.",
      languages: ["Portoghese", "Inglese"],
      tags: ["M&A", "Societario", "Contratti"],
      included: "Consulenza strategica riservata con analisi preliminare dei documenti inviati.",
      historyAt: ["22 min fa", "1h fa", "3h fa"],
    },
  },
  ja: {
    "1": {
      niche: "健康",
      specialty: "循環器専門医 — エグゼクティブ健診",
      credential: "ハーバード大学医学部 博士研究員",
      bio: "22年以上にわたり高水準の予防循環器学に従事し、サンパウロとニューヨークで経営幹部やアスリートを診察。",
      languages: ["ポルトガル語", "英語"],
      tags: ["循環器学", "健診", "予防"],
      included: "最近の検査の詳細な分析、パーソナライズされたフォローアッププラン、48時間以内のエグゼクティブレポート。",
      historyAt: ["4分前", "11分前", "28分前", "1時間前"],
    },
    "2": {
      niche: "音楽",
      specialty: "音楽プロデューサー — デモ分析",
      credential: "2019年ラテン・グラミー賞",
      bio: "スタジオ歴30年のプロデューサー。ブラジリアン・ポップ、ジャズ、現代クラシック音楽の受賞アーティストと仕事をしてきました。",
      languages: ["ポルトガル語", "英語", "スペイン語"],
      tags: ["プロダクション", "デモ", "ミキシング"],
      included: "あなたのデモの批評的な試聴、プロダクションの提案、90分のセッションでのアーティスティックディレクション。",
      historyAt: ["12分前", "40分前", "2時間前"],
    },
    "3": {
      niche: "テクノロジー",
      specialty: "ソフトウェアアーキテクト — コードレビュー",
      credential: "元Googleスタッフエンジニア",
      bio: "分散システムと大規模アーキテクチャの専門家。Y Combinator創業者のメンター。",
      languages: ["ポルトガル語", "英語"],
      tags: ["アーキテクチャ", "コードレビュー", "メンタリング"],
      included: "ライブコードレビュー、アーキテクチャレビュー、優先順位付けされた改善ロードマップ。",
      historyAt: ["2分前", "18分前", "35分前"],
    },
    "4": {
      niche: "法律",
      specialty: "企業法務・M&A",
      credential: "一流法律事務所パートナー",
      bio: "ブラジル最大級の法律事務所のパートナーで、合併・買収・会社組織再編を専門とする。",
      languages: ["ポルトガル語", "英語"],
      tags: ["M&A", "会社法", "契約"],
      included: "提出書類の事前分析を含む機密の戦略コンサルティング。",
      historyAt: ["22分前", "1時間前", "3時間前"],
    },
  },
  zh: {
    "1": {
      niche: "健康",
      specialty: "心脏科医生 — 高管体检",
      credential: "哈佛医学院博士后",
      bio: "拥有超过22年高水准预防心脏病学经验，在圣保罗和纽约为高管及运动员提供诊疗服务。",
      languages: ["葡萄牙语", "英语"],
      tags: ["心脏病学", "体检", "预防"],
      included: "全面分析近期检查结果，制定个性化跟进方案，并在48小时内提供高管报告。",
      historyAt: ["4分钟前", "11分钟前", "28分钟前", "1小时前"],
    },
    "2": {
      niche: "音乐",
      specialty: "音乐制作人 — 试听带分析",
      credential: "2019年拉丁格莱美奖",
      bio: "拥有三十年录音室经验的制作人，曾与巴西流行、爵士及当代古典音乐的获奖艺术家合作。",
      languages: ["葡萄牙语", "英语", "西班牙语"],
      tags: ["制作", "试听带", "混音"],
      included: "对您的试听带进行专业点评、提供制作建议，并在90分钟会话中给予艺术指导。",
      historyAt: ["12分钟前", "40分钟前", "2小时前"],
    },
    "3": {
      niche: "科技",
      specialty: "软件架构师 — 代码审查",
      credential: "前谷歌高级工程师",
      bio: "分布式系统与大规模架构专家，Y Combinator 创始人导师。",
      languages: ["葡萄牙语", "英语"],
      tags: ["架构", "代码审查", "指导"],
      included: "实时代码审查、架构评审及优先改进路线图。",
      historyAt: ["2分钟前", "18分钟前", "35分钟前"],
    },
    "4": {
      niche: "法律",
      specialty: "企业法与并购业务",
      credential: "一线律所合伙人",
      bio: "巴西顶尖律师事务所合伙人，专精于并购及公司架构设计。",
      languages: ["葡萄牙语", "英语"],
      tags: ["并购", "公司法", "合同"],
      included: "在审阅所提交文件后提供保密战略咨询。",
      historyAt: ["22分钟前", "1小时前", "3小时前"],
    },
  },
  ar: {
    "1": {
      niche: "الصحة",
      specialty: "طبيبة قلب — فحص تنفيذي",
      credential: "زمالة بحثية في كلية هارفارد الطبية",
      bio: "أكثر من 22 عامًا مكرّسة لطب القلب الوقائي عالي الأداء، تخدم المدراء التنفيذيين والرياضيين في ساو باولو ونيويورك.",
      languages: ["البرتغالية", "الإنجليزية"],
      tags: ["طب القلب", "فحص", "الوقاية"],
      included: "تحليل شامل للفحوصات الأخيرة، وخطة متابعة مخصصة، وتقرير تنفيذي يُسلَّم خلال 48 ساعة.",
      historyAt: ["قبل 4 دقائق", "قبل 11 دقيقة", "قبل 28 دقيقة", "قبل ساعة"],
    },
    "2": {
      niche: "الموسيقى",
      specialty: "منتج موسيقي — تحليل العرض التجريبي",
      credential: "جرامي لاتيني 2019",
      bio: "منتج بخبرة ثلاثة عقود في الاستوديو. عمل مع فنانين حائزين على جوائز في موسيقى البوب البرازيلية والجاز والموسيقى الكلاسيكية المعاصرة.",
      languages: ["البرتغالية", "الإنجليزية", "الإسبانية"],
      tags: ["الإنتاج", "العرض التجريبي", "المزج"],
      included: "استماع نقدي لعرضك التجريبي، اقتراحات إنتاج، وتوجيه فني في جلسة مدتها 90 دقيقة.",
      historyAt: ["قبل 12 دقيقة", "قبل 40 دقيقة", "قبل ساعتين"],
    },
    "3": {
      niche: "التكنولوجيا",
      specialty: "مهندس معماري للبرمجيات — مراجعة الكود",
      credential: "مهندس أول سابق في Google",
      bio: "متخصص في الأنظمة الموزعة والهندسة المعمارية واسعة النطاق. موجّه لمؤسسي Y Combinator.",
      languages: ["البرتغالية", "الإنجليزية"],
      tags: ["الهندسة المعمارية", "مراجعة الكود", "التوجيه"],
      included: "مراجعة كود مباشرة، مراجعة معمارية، وخارطة طريق للتحسينات ذات الأولوية.",
      historyAt: ["قبل دقيقتين", "قبل 18 دقيقة", "قبل 35 دقيقة"],
    },
    "4": {
      niche: "القانون",
      specialty: "قانون الشركات والاندماج والاستحواذ",
      credential: "شريكة في مكتب محاماة من الطراز الأول",
      bio: "شريكة في أحد أكبر مكاتب المحاماة في البرازيل، متخصصة في الاندماج والاستحواذ والهيكلة المؤسسية.",
      languages: ["البرتغالية", "الإنجليزية"],
      tags: ["اندماج واستحواذ", "قانون الشركات", "العقود"],
      included: "استشارة استراتيجية سرية مع مراجعة مسبقة للمستندات المرسلة.",
      historyAt: ["قبل 22 دقيقة", "قبل ساعة", "قبل 3 ساعات"],
    },
  },
};

export function useLocalizedAuction(auction: Auction, lang: LangCode): Auction {
  const overrides = AUCTION_I18N[lang]?.[auction.id];
  if (!overrides) return auction;
  return {
    ...auction,
    niche: overrides.niche,
    specialty: overrides.specialty,
    credential: overrides.credential,
    bio: overrides.bio,
    languages: overrides.languages,
    tags: overrides.tags,
    included: overrides.included,
    history: auction.history.map((h, i) => ({ value: h.value, at: overrides.historyAt[i] ?? h.at })),
  };
}
